version: '3.4'

services:
    identitydb:
        container_name: identitydb_cont
        restart: always
        ports:
            - "3232:5432" 
        volumes:
            - identitydb_volume:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=identitydb
            - POSTGRES_USER=ndg
            - POSTGRES_PASSWORD=NDGSTUDIOPOSTGRESFORAWS
    progressdb:
        container_name: progressdb_cont
        restart: always
        ports:
            - "3233:5432" 
        volumes:
            - progressdb_volume:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=progressdb
            - POSTGRES_USER=ndg
            - POSTGRES_PASSWORD=NDGSTUDIOPOSTGRESFORAWS
    playerbasedb:
        container_name: playerbasedb_cont
        restart: always
        ports:
            - "3234:5432" 
        volumes:
            - playerbasedb_volume:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=playerbasedb
            - POSTGRES_USER=ndg
            - POSTGRES_PASSWORD=NDGSTUDIOPOSTGRESFORAWS
    identityapi:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
        ports:
            - "5000:80"
            - "5001:443"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        depends_on:
            - identitydb
    progressapi:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
        ports:
            - "5002:80"
            - "5003:443"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        depends_on:
            - progressdb
    playerbaseapi:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
        ports:
            - "5004:80"
            - "5005:443"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        depends_on:
            - playerbasedb