version: '3.4'

services:
    postgresdb:
        image: postgres
    identityapi:
        image: identityapi
        build:
            context: .
            dockerfile: IdentityApi/Dockerfile
        environment:
            - ConnectionStrings:IdentityContext=User Id=postgres;Password=NDGSTUDIOPOSTGRESFORAWS;Server=postgresdb;Port=5432;Database=postgres;Integrated Security=true;Pooling=true;
            - JWTSECRET=ApplicationSecretWhichUsed4Authentication.JwtToken*?xx23.45dsajdnjaIsykKhJdyshahbBHSBDA.HBDSHA33X3SJDNJSAKU.WHDEWO2348nG2mS9ASDrA34oS5D.J.SAD
volumes:
    postgresdb_volume: