version: '3.4'

services:
    identitydb:
        image: postgres
    identityapi:
        image: identityapi
        build:
            context: .
            dockerfile: IdentityApi/Dockerfile
        environment:
            - ConnectionStrings__IdentityContext=User Id=ndg;Password=NDGSTUDIOPOSTGRESFORAWS;Server=identitydb;Port=5432;Database=identitydb;Integrated Security=true;Pooling=true;
            - JWTSECRET=ApplicationSecretWhichUsed4Authentication.JwtToken*?xx23.45dsajdnjaIsykKhJdyshahbBHSBDA.HBDSHA33X3SJDNJSAKU.WHDEWO2348nG2mS9ASDrA34oS5D.J.SAD
volumes:
    identitydb_volume: