version: '3.4'

#networks:
#  isolation-network:
#    driver: bridge

services:
    identitydb:
        image: postgres
        mem_limit: 1g
        #networks:
        #    - isolation-network
    progressdb:
        image: postgres
        mem_limit: 1g
        #networks:
        #    - isolation-network
    identityapi:
        #networks:
        #    - isolation-network
        image: ugurcanbagriyanik/identityapi
        mem_limit: 1g
        build:
            context: .
            dockerfile: IdentityApi/Dockerfile
        environment:
            - ConnectionStrings__IdentityContext=User Id=ndg;Password=NDGSTUDIOPOSTGRESFORAWS;Server=identitydb;Port=5432;Database=identitydb;Integrated Security=true;Pooling=true;
            - JWTSECRET=ApplicationSecretWhichUsed4Authentication.JwtToken*?xx23.45dsajdnjaIsykKhJdyshahbBHSBDA.HBDSHA33X3SJDNJSAKU.WHDEWO2348nG2mS9ASDrA34oS5D.J.SAD
    progressapi:
        #networks:
        #    - isolation-network
        image: ugurcanbagriyanik/progressapi
        mem_limit: 1g
        build:
            context: .
            dockerfile: ProgressApi/Dockerfile
        environment:
            - ConnectionStrings__ProgressContext=User Id=ndg;Password=NDGSTUDIOPOSTGRESFORAWS;Server=progressdb;Port=5432;Database=progressdb;Integrated Security=true;Pooling=true;
            - IdentityEndpoint=https://identityapi
volumes:
    identitydb_volume:
    progressdb_volume: