version: '3.4'

services:
    identitydb:
        container_name: identitydb_cont
        restart: always
        ports:
            - "3232:5432" 
        volumes:
            - identitydb_volume:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=identitydb
            - POSTGRES_USER=ndg
            - POSTGRES_PASSWORD=NDGSTUDIOPOSTGRESFORAWS
    identityapi:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
        ports:
            - "80"
            - "443"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        depends_on:
            - identitydb