version: '3.4'

services:
    postgresdb:
        container_name: postgresdb_cont
        restart: always
        ports:
            - "3232:5432" 
        volumes:
            - postgresdb_volume:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=NDGSTUDIOPOSTGRESFORAWS
            - POSTGRES_DB=postgres
    identityapi:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
        ports:
            - "80"
            - "443"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        depends_on:
            - postgresdb