// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlayerBaseApi;

#nullable disable

namespace PlayerBaseApi.Migrations
{
    [DbContext(typeof(PlayerBaseContext))]
    [Migration("20221021145354_herocard-rarity-added")]
    partial class herocardrarityadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlayerBaseApi.Entities.Buff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AttackMultiplier")
                        .HasColumnType("double precision");

                    b.Property<bool>("AutoLootRunActive")
                        .HasColumnType("boolean");

                    b.Property<double>("BaseResourceMultiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("BuildingUpgradeCostMultiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("BuildingUpgradeDurationMultiplier")
                        .HasColumnType("double precision");

                    b.Property<bool>("CityShieldActive")
                        .HasColumnType("boolean");

                    b.Property<double>("DefenseMultiplier")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("LootBluePrintMultiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("LootCapacity")
                        .HasColumnType("double precision");

                    b.Property<double>("LootDurationMultiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("LootGemMultiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("LootPerfectRunMultiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("LootScrapMultiplier")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PrisonCapacityMultiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("PrisonCostMultiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("PrisonExecutionEarnMultiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("PrisonTrainingCostMultiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("PrisonTrainingDurationMultiplier")
                        .HasColumnType("double precision");

                    b.Property<double>("SpyFakerMultiplier")
                        .HasColumnType("double precision");

                    b.Property<bool>("SpyProtectionActive")
                        .HasColumnType("boolean");

                    b.Property<double>("TroopCapacityMultiplier")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Buff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttackMultiplier = 0.0,
                            AutoLootRunActive = false,
                            BaseResourceMultiplier = 0.0,
                            BuildingUpgradeCostMultiplier = 0.0,
                            BuildingUpgradeDurationMultiplier = 0.0,
                            CityShieldActive = false,
                            DefenseMultiplier = 0.0,
                            Description = "",
                            LootBluePrintMultiplier = 0.0,
                            LootCapacity = 0.0,
                            LootDurationMultiplier = 0.0,
                            LootGemMultiplier = 0.0,
                            LootPerfectRunMultiplier = 0.0,
                            LootScrapMultiplier = 0.0,
                            Name = "0-Buff",
                            PrisonCapacityMultiplier = 0.0,
                            PrisonCostMultiplier = 0.0,
                            PrisonExecutionEarnMultiplier = 0.0,
                            PrisonTrainingCostMultiplier = 0.0,
                            PrisonTrainingDurationMultiplier = 0.0,
                            SpyFakerMultiplier = 0.0,
                            SpyProtectionActive = false,
                            TroopCapacityMultiplier = 0.0
                        });
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.BuildingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BuildUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BuildingType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2021/09/h1-client-img-5.png",
                            IsActive = true,
                            MaxLevel = 1000,
                            Name = "Base"
                        },
                        new
                        {
                            Id = 2,
                            BuildUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2021/09/h1-client-img-4.png",
                            IsActive = true,
                            MaxLevel = 1000,
                            Name = "Gang Tower"
                        },
                        new
                        {
                            Id = 3,
                            BuildUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2021/09/h1-client-img-4.png",
                            IsActive = true,
                            MaxLevel = 1000,
                            Name = "Wall"
                        },
                        new
                        {
                            Id = 4,
                            BuildUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2021/09/h1-client-img-4.png",
                            IsActive = true,
                            MaxLevel = 1000,
                            Name = "Hospital"
                        },
                        new
                        {
                            Id = 5,
                            BuildUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2021/09/h1-client-img-4.png",
                            IsActive = true,
                            MaxLevel = 1000,
                            Name = "Prison"
                        },
                        new
                        {
                            Id = 6,
                            BuildUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2021/09/h1-client-img-6.png",
                            IsActive = true,
                            MaxLevel = 1000,
                            Name = "Market"
                        },
                        new
                        {
                            Id = 7,
                            BuildUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2021/09/h1-client-img-4.png",
                            IsActive = true,
                            MaxLevel = 1000,
                            Name = "Altar"
                        },
                        new
                        {
                            Id = 8,
                            BuildUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2021/09/h1-client-img-4.png",
                            IsActive = true,
                            MaxLevel = 1000,
                            Name = "Watch Tower"
                        },
                        new
                        {
                            Id = 9,
                            BuildUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2021/09/h1-client-img-4.png",
                            IsActive = true,
                            MaxLevel = 1000,
                            Name = "Research Laboratory"
                        },
                        new
                        {
                            Id = 10,
                            BuildUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2021/09/h1-client-img-4.png",
                            IsActive = true,
                            MaxLevel = 1000,
                            Name = "Military Base"
                        });
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.BuildingUpgradeTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("ScrapCount")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("UpgradeDuration")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("BuildingTypeId");

                    b.ToTable("BuildingUpgradeTime");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.Dialog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnimId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DialogSceneId")
                        .HasColumnType("integer");

                    b.Property<int>("HeroId")
                        .HasColumnType("integer");

                    b.Property<int>("PlaceId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DialogSceneId");

                    b.HasIndex("HeroId");

                    b.ToTable("Dialog");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.DialogScene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DialogSceneCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DialogScene");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundPictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsApe")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Story")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThemeColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hero");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackgroundPictureUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2022/09/Background-min-scaled.jpg",
                            Description = "dummydescription",
                            IsActive = true,
                            IsApe = false,
                            MaxLevel = 30,
                            Name = "Zeus",
                            Story = "Dummyherostory",
                            ThemeColor = "#993333",
                            ThumbnailUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2018/06/h2-custom-icon-img-1.png"
                        },
                        new
                        {
                            Id = 2,
                            BackgroundPictureUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2022/09/Background-min-scaled.jpg",
                            Description = "Hadesdescription",
                            IsActive = true,
                            IsApe = false,
                            MaxLevel = 30,
                            Name = "Hades",
                            Story = "Hadesherostory",
                            ThemeColor = "#2F4F4F",
                            ThumbnailUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2018/06/h2-custom-icon-img-2-100x100.png"
                        },
                        new
                        {
                            Id = 3,
                            BackgroundPictureUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2022/09/Background-min-scaled.jpg",
                            Description = "Poseidondescription",
                            IsActive = true,
                            IsApe = false,
                            MaxLevel = 30,
                            Name = "Poseidon",
                            Story = "Poseidonherostory",
                            ThemeColor = "#00FFFF",
                            ThumbnailUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2018/06/h2-custom-icon-img-3-100x100.png"
                        },
                        new
                        {
                            Id = 4,
                            BackgroundPictureUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2022/09/Background-min-scaled.jpg",
                            Description = "Odindescription",
                            IsActive = true,
                            IsApe = false,
                            MaxLevel = 30,
                            Name = "Odin",
                            Story = "Odinherostory",
                            ThemeColor = "#993333",
                            ThumbnailUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2018/06/h2-custom-icon-img-1.png"
                        },
                        new
                        {
                            Id = 5,
                            BackgroundPictureUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2022/09/Background-min-scaled.jpg",
                            Description = "Thordescription",
                            IsActive = true,
                            IsApe = false,
                            MaxLevel = 30,
                            Name = "Thor",
                            Story = "Thorherostory",
                            ThemeColor = "#993333",
                            ThumbnailUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2018/06/h2-custom-icon-img-1.png"
                        },
                        new
                        {
                            Id = 6,
                            BackgroundPictureUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2022/09/Background-min-scaled.jpg",
                            Description = "Smasher",
                            IsActive = true,
                            IsApe = true,
                            MaxLevel = 30,
                            Name = "Hulk",
                            Story = "Hulkherostory",
                            ThemeColor = "#006400",
                            ThumbnailUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2018/06/h2-custom-icon-img-1.png"
                        },
                        new
                        {
                            Id = 7,
                            BackgroundPictureUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2022/09/Background-min-scaled.jpg",
                            Description = "Abominationdescription",
                            IsActive = true,
                            IsApe = true,
                            MaxLevel = 30,
                            Name = "Abomination",
                            Story = "Abominationherostory",
                            ThemeColor = "#7CFC00",
                            ThumbnailUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2018/06/h2-custom-icon-img-1.png"
                        },
                        new
                        {
                            Id = 8,
                            BackgroundPictureUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2022/09/Background-min-scaled.jpg",
                            Description = "octopusdescription",
                            IsActive = true,
                            IsApe = true,
                            MaxLevel = 30,
                            Name = "Dr. Octopus",
                            Story = "Octopusherostory",
                            ThemeColor = "#778899",
                            ThumbnailUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2018/06/h2-custom-icon-img-1.png"
                        },
                        new
                        {
                            Id = 9,
                            BackgroundPictureUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2022/09/Background-min-scaled.jpg",
                            Description = "Just Joker",
                            IsActive = true,
                            IsApe = true,
                            MaxLevel = 30,
                            Name = "Joker",
                            Story = "Dramatic Hero Story",
                            ThemeColor = "#FF8C00",
                            ThumbnailUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2018/06/h2-custom-icon-img-1.png"
                        },
                        new
                        {
                            Id = 10,
                            BackgroundPictureUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2022/09/Background-min-scaled.jpg",
                            Description = "Black Noir description",
                            IsActive = true,
                            IsApe = true,
                            MaxLevel = 30,
                            Name = "Black Noir",
                            Story = "Black Noir herostory",
                            ThemeColor = "#000000",
                            ThumbnailUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2018/06/h2-custom-icon-img-1.png"
                        },
                        new
                        {
                            Id = 11,
                            BackgroundPictureUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2022/09/Background-min-scaled.jpg",
                            Description = "Invinsible Gauntlet Lover",
                            IsActive = false,
                            IsApe = true,
                            MaxLevel = 30,
                            Name = "Thanos",
                            Story = "Long Story",
                            ThemeColor = "#8A2BE2",
                            ThumbnailUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2018/06/h2-custom-icon-img-1.png"
                        });
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.HeroLevelThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuffId")
                        .HasColumnType("integer");

                    b.Property<long>("Experience")
                        .HasColumnType("bigint");

                    b.Property<int>("HeroId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuffId");

                    b.HasIndex("HeroId");

                    b.ToTable("HeroLevelThreshold");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.HeroSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HeroId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPassiveSkill")
                        .HasColumnType("boolean");

                    b.Property<int>("MaksLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlaceId")
                        .HasColumnType("integer");

                    b.Property<string>("TumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("HeroSkill");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.HeroSkillLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuffId")
                        .HasColumnType("integer");

                    b.Property<int>("HeroSkillId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuffId");

                    b.HasIndex("HeroSkillId");

                    b.ToTable("HeroSkillLevel");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.HospitalLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("HealingCostPerUnit")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("HealingDurationPerUnit")
                        .HasColumnType("interval");

                    b.Property<int>("HospitalCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("HospitalLevel");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Value1")
                        .HasColumnType("integer");

                    b.Property<int?>("Value2")
                        .HasColumnType("integer");

                    b.Property<int?>("Value3")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.ItemCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ItemCategory");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConsumable")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemCategoryId");

                    b.ToTable("ItemType");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.LootLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("LootDuration")
                        .HasColumnType("interval");

                    b.Property<int>("MaxBlueprintCount")
                        .HasColumnType("integer");

                    b.Property<int>("MaxGemCount")
                        .HasColumnType("integer");

                    b.Property<int>("MaxScrapCount")
                        .HasColumnType("integer");

                    b.Property<int>("MinBlueprintCount")
                        .HasColumnType("integer");

                    b.Property<int>("MinGemCount")
                        .HasColumnType("integer");

                    b.Property<int>("MinScrapCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LootLevel");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.MarketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GemPrice")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCount")
                        .HasColumnType("integer");

                    b.Property<int>("ScrapPrice")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("MarketItem");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerBaseInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("BaseFullDuration")
                        .HasColumnType("interval");

                    b.Property<int>("BaseLevel")
                        .HasColumnType("integer");

                    b.Property<int>("BluePrints")
                        .HasColumnType("integer");

                    b.Property<int>("EpicHeroCards")
                        .HasColumnType("integer");

                    b.Property<int>("Fuel")
                        .HasColumnType("integer");

                    b.Property<int>("Gems")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastBaseCollect")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LegendaryHeroCards")
                        .HasColumnType("integer");

                    b.Property<int>("RareHeroCards")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceProductionPerHour")
                        .HasColumnType("integer");

                    b.Property<int>("Scraps")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PlayerBaseInfo");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerBasePlacement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BuildingLevel")
                        .HasColumnType("integer");

                    b.Property<int>("BuildingTypeId")
                        .HasColumnType("integer");

                    b.Property<double>("CoordX")
                        .HasColumnType("double precision");

                    b.Property<double>("CoordY")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("UpdateEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BuildingTypeId");

                    b.ToTable("PlayerBasePlacement");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BuildingLevel = 1,
                            BuildingTypeId = 1,
                            CoordX = 1.0,
                            CoordY = 1.0,
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerBuff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuffId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BuffId");

                    b.ToTable("PlayerBuff");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerHero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Exp")
                        .HasColumnType("bigint");

                    b.Property<int>("HeroId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillPoint")
                        .HasColumnType("integer");

                    b.Property<int>("TalentPoint")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("HeroId");

                    b.ToTable("PlayerHero");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerHeroLoot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GainedResources")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LootLevelId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OperationEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OperationStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlayerHeroId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LootLevelId");

                    b.HasIndex("PlayerHeroId");

                    b.ToTable("PlayerHeroLoot");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerHeroSkillLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HeroSkillLevelId")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("HeroSkillLevelId");

                    b.ToTable("PlayerHeroSkillLevel");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerHospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("HealingDoneDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HospitalLevelId")
                        .HasColumnType("integer");

                    b.Property<int>("InHealingCount")
                        .HasColumnType("integer");

                    b.Property<int>("InjuredCount")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("HospitalLevelId");

                    b.ToTable("PlayerHospital");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("PlayerItem");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerMarketHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AfterGemCount")
                        .HasColumnType("integer");

                    b.Property<int>("AfterScrapCount")
                        .HasColumnType("integer");

                    b.Property<int>("BeforeGemCount")
                        .HasColumnType("integer");

                    b.Property<int>("BeforeScrapCount")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("MarketItemId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MarketItemId");

                    b.ToTable("PlayerMarketHistory");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerPrison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InTrainingPrisonerCount")
                        .HasColumnType("integer");

                    b.Property<int>("PrisonLevelId")
                        .HasColumnType("integer");

                    b.Property<int>("PrisonerCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("TrainingDoneDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PrisonLevelId");

                    b.ToTable("PlayerPrison");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerResearchNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("integer");

                    b.Property<int>("ResearchNodeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdateEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ResearchNodeId");

                    b.ToTable("PlayerResearchNode");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerTalentTreeNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("TalentTreeNodeId")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TalentTreeNodeId");

                    b.ToTable("PlayerTalentTreeNode");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerTroop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TroopCount")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("PlayerTroop");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PrisonLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuffId")
                        .HasColumnType("integer");

                    b.Property<double>("ExecutionEarnPerUnit")
                        .HasColumnType("double precision");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MaxPrisonerCount")
                        .HasColumnType("integer");

                    b.Property<double>("TrainingCostPerUnit")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("TrainingDurationPerUnit")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("BuffId");

                    b.ToTable("PrisonLevel");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.ResearchNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuffId")
                        .HasColumnType("integer");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlaceId")
                        .HasColumnType("integer");

                    b.Property<int>("ResearchTableId")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BuffId");

                    b.HasIndex("ResearchTableId");

                    b.ToTable("ResearchNode");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.ResearchNodeUpgradeCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BuildingTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("PrereqLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("ResearchNodeId")
                        .HasColumnType("integer");

                    b.Property<int>("ResearchNodeUpgradeNecessariesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingTypeId");

                    b.HasIndex("ResearchNodeId");

                    b.HasIndex("ResearchNodeUpgradeNecessariesId");

                    b.ToTable("ResearchNodeUpgradeCondition");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.ResearchNodeUpgradeNecessaries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BluePrintCount")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<int>("ResearchNodeId")
                        .HasColumnType("integer");

                    b.Property<int>("ScrapCount")
                        .HasColumnType("integer");

                    b.Property<int>("UpgradeLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResearchNodeId");

                    b.ToTable("ResearchNodeUpgradeNecessaries");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.ResearchTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ResearchTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Military Research",
                            ThumbnailUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2021/09/h1-client-img-6.png"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Economical Research",
                            ThumbnailUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2021/09/h1-client-img-6.png"
                        },
                        new
                        {
                            Id = 3,
                            Name = "General Research",
                            ThumbnailUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2021/09/h1-client-img-6.png"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tower Defense Research",
                            ThumbnailUrl = "https://gaming.ndgstudio.com.tr/wp-content/uploads/2021/09/h1-client-img-6.png"
                        });
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.TalentTree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ThemeColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TalentTree");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.TalentTreeNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuffId")
                        .HasColumnType("integer");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HeroId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlaceId")
                        .HasColumnType("integer");

                    b.Property<int>("TalentTreeId")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BuffId");

                    b.HasIndex("HeroId");

                    b.HasIndex("TalentTreeId");

                    b.ToTable("TalentTreeNode");
                });

            modelBuilder.Entity("SharedLibrary.Entities.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text");

                    b.Property<string>("AppVersion")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<string>("DeviceModel")
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text");

                    b.Property<double?>("Duration")
                        .HasColumnType("double precision");

                    b.Property<string>("EventId")
                        .HasColumnType("text");

                    b.Property<string>("EventName")
                        .HasColumnType("text");

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<string>("InnerException")
                        .HasColumnType("text");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OsVersion")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("SharedLibrary.Entities.LogAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text");

                    b.Property<string>("AppVersion")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<string>("DeviceModel")
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text");

                    b.Property<double?>("Duration")
                        .HasColumnType("double precision");

                    b.Property<string>("EventId")
                        .HasColumnType("text");

                    b.Property<string>("EventName")
                        .HasColumnType("text");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OsVersion")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("LogAction");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.BuildingUpgradeTime", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.BuildingType", "BuildingType")
                        .WithMany()
                        .HasForeignKey("BuildingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildingType");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.Dialog", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.DialogScene", "DialogScene")
                        .WithMany()
                        .HasForeignKey("DialogSceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayerBaseApi.Entities.Hero", "Hero")
                        .WithMany()
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DialogScene");

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.HeroLevelThreshold", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.Buff", "Buff")
                        .WithMany()
                        .HasForeignKey("BuffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayerBaseApi.Entities.Hero", "Hero")
                        .WithMany()
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buff");

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.HeroSkill", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.Hero", "Hero")
                        .WithMany()
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.HeroSkillLevel", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.Buff", "Buff")
                        .WithMany()
                        .HasForeignKey("BuffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayerBaseApi.Entities.HeroSkill", "HeroSkill")
                        .WithMany()
                        .HasForeignKey("HeroSkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buff");

                    b.Navigation("HeroSkill");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.Item", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.ItemType", "ItemType")
                        .WithMany()
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.ItemType", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.ItemCategory", "ItemCategory")
                        .WithMany()
                        .HasForeignKey("ItemCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemCategory");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.MarketItem", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerBasePlacement", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.BuildingType", "BuildingType")
                        .WithMany()
                        .HasForeignKey("BuildingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildingType");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerBuff", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.Buff", "Buff")
                        .WithMany()
                        .HasForeignKey("BuffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buff");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerHero", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.Hero", "Hero")
                        .WithMany()
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hero");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerHeroLoot", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.LootLevel", "LootLevel")
                        .WithMany()
                        .HasForeignKey("LootLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayerBaseApi.Entities.PlayerHero", "PlayerHero")
                        .WithMany()
                        .HasForeignKey("PlayerHeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LootLevel");

                    b.Navigation("PlayerHero");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerHeroSkillLevel", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.HeroSkillLevel", "HeroSkillLevel")
                        .WithMany()
                        .HasForeignKey("HeroSkillLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeroSkillLevel");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerHospital", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.HospitalLevel", "HospitalLevel")
                        .WithMany()
                        .HasForeignKey("HospitalLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HospitalLevel");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerItem", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerMarketHistory", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.MarketItem", "MarketItem")
                        .WithMany()
                        .HasForeignKey("MarketItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketItem");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerPrison", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.PrisonLevel", "PrisonLevel")
                        .WithMany()
                        .HasForeignKey("PrisonLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrisonLevel");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerResearchNode", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.ResearchNode", "ResearchNode")
                        .WithMany()
                        .HasForeignKey("ResearchNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResearchNode");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PlayerTalentTreeNode", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.TalentTreeNode", "TalentTreeNode")
                        .WithMany()
                        .HasForeignKey("TalentTreeNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TalentTreeNode");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.PrisonLevel", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.Buff", "Buff")
                        .WithMany()
                        .HasForeignKey("BuffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buff");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.ResearchNode", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.Buff", "Buff")
                        .WithMany()
                        .HasForeignKey("BuffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayerBaseApi.Entities.ResearchTable", "ResearchTable")
                        .WithMany()
                        .HasForeignKey("ResearchTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buff");

                    b.Navigation("ResearchTable");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.ResearchNodeUpgradeCondition", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.BuildingType", "BuildingType")
                        .WithMany()
                        .HasForeignKey("BuildingTypeId");

                    b.HasOne("PlayerBaseApi.Entities.ResearchNode", "ResearchNode")
                        .WithMany()
                        .HasForeignKey("ResearchNodeId");

                    b.HasOne("PlayerBaseApi.Entities.ResearchNodeUpgradeNecessaries", "ResearchNodeUpgradeNecessaries")
                        .WithMany()
                        .HasForeignKey("ResearchNodeUpgradeNecessariesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuildingType");

                    b.Navigation("ResearchNode");

                    b.Navigation("ResearchNodeUpgradeNecessaries");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.ResearchNodeUpgradeNecessaries", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.ResearchNode", "ResearchNode")
                        .WithMany()
                        .HasForeignKey("ResearchNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResearchNode");
                });

            modelBuilder.Entity("PlayerBaseApi.Entities.TalentTreeNode", b =>
                {
                    b.HasOne("PlayerBaseApi.Entities.Buff", "Buff")
                        .WithMany()
                        .HasForeignKey("BuffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayerBaseApi.Entities.Hero", "Hero")
                        .WithMany()
                        .HasForeignKey("HeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayerBaseApi.Entities.TalentTree", "TalentTree")
                        .WithMany()
                        .HasForeignKey("TalentTreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buff");

                    b.Navigation("Hero");

                    b.Navigation("TalentTree");
                });
#pragma warning restore 612, 618
        }
    }
}
