// <auto-generated />
using System;
using MapApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MapApi.Migrations
{
    [DbContext(typeof(MapContext))]
    [Migration("20220908085353_gridsys-minimaze-fixed")]
    partial class gridsysminimazefixed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MapApi.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("XMax")
                        .HasColumnType("integer");

                    b.Property<int>("XMin")
                        .HasColumnType("integer");

                    b.Property<int>("YMax")
                        .HasColumnType("integer");

                    b.Property<int>("YMin")
                        .HasColumnType("integer");

                    b.Property<int>("ZoneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Area");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            XMax = 15,
                            XMin = 0,
                            YMax = 15,
                            YMin = 0,
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 2,
                            XMax = 30,
                            XMin = 15,
                            YMax = 15,
                            YMin = 0,
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 3,
                            XMax = 45,
                            XMin = 30,
                            YMax = 15,
                            YMin = 0,
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 4,
                            XMax = 15,
                            XMin = 0,
                            YMax = 30,
                            YMin = 15,
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 5,
                            XMax = 30,
                            XMin = 15,
                            YMax = 30,
                            YMin = 15,
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 6,
                            XMax = 45,
                            XMin = 30,
                            YMax = 30,
                            YMin = 15,
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 7,
                            XMax = 15,
                            XMin = 0,
                            YMax = 45,
                            YMin = 30,
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 8,
                            XMax = 30,
                            XMin = 15,
                            YMax = 45,
                            YMin = 30,
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 9,
                            XMax = 45,
                            XMin = 30,
                            YMax = 45,
                            YMin = 30,
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 10,
                            XMax = 60,
                            XMin = 45,
                            YMax = 15,
                            YMin = 0,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 11,
                            XMax = 75,
                            XMin = 60,
                            YMax = 15,
                            YMin = 0,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 12,
                            XMax = 90,
                            XMin = 75,
                            YMax = 15,
                            YMin = 0,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 13,
                            XMax = 60,
                            XMin = 45,
                            YMax = 30,
                            YMin = 15,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 14,
                            XMax = 75,
                            XMin = 60,
                            YMax = 30,
                            YMin = 15,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 15,
                            XMax = 90,
                            XMin = 75,
                            YMax = 30,
                            YMin = 15,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 16,
                            XMax = 60,
                            XMin = 45,
                            YMax = 45,
                            YMin = 30,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 17,
                            XMax = 75,
                            XMin = 60,
                            YMax = 45,
                            YMin = 30,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 18,
                            XMax = 90,
                            XMin = 75,
                            YMax = 45,
                            YMin = 30,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 19,
                            XMax = 105,
                            XMin = 90,
                            YMax = 15,
                            YMin = 0,
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 20,
                            XMax = 120,
                            XMin = 105,
                            YMax = 15,
                            YMin = 0,
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 21,
                            XMax = 135,
                            XMin = 120,
                            YMax = 15,
                            YMin = 0,
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 22,
                            XMax = 105,
                            XMin = 90,
                            YMax = 30,
                            YMin = 15,
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 23,
                            XMax = 120,
                            XMin = 105,
                            YMax = 30,
                            YMin = 15,
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 24,
                            XMax = 135,
                            XMin = 120,
                            YMax = 30,
                            YMin = 15,
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 25,
                            XMax = 105,
                            XMin = 90,
                            YMax = 45,
                            YMin = 30,
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 26,
                            XMax = 120,
                            XMin = 105,
                            YMax = 45,
                            YMin = 30,
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 27,
                            XMax = 135,
                            XMin = 120,
                            YMax = 45,
                            YMin = 30,
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 28,
                            XMax = 15,
                            XMin = 0,
                            YMax = 60,
                            YMin = 45,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 29,
                            XMax = 30,
                            XMin = 15,
                            YMax = 60,
                            YMin = 45,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 30,
                            XMax = 45,
                            XMin = 30,
                            YMax = 60,
                            YMin = 45,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 31,
                            XMax = 15,
                            XMin = 0,
                            YMax = 75,
                            YMin = 60,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 32,
                            XMax = 30,
                            XMin = 15,
                            YMax = 75,
                            YMin = 60,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 33,
                            XMax = 45,
                            XMin = 30,
                            YMax = 75,
                            YMin = 60,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 34,
                            XMax = 15,
                            XMin = 0,
                            YMax = 90,
                            YMin = 75,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 35,
                            XMax = 30,
                            XMin = 15,
                            YMax = 90,
                            YMin = 75,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 36,
                            XMax = 45,
                            XMin = 30,
                            YMax = 90,
                            YMin = 75,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 37,
                            XMax = 60,
                            XMin = 45,
                            YMax = 60,
                            YMin = 45,
                            ZoneId = 5
                        },
                        new
                        {
                            Id = 38,
                            XMax = 75,
                            XMin = 60,
                            YMax = 60,
                            YMin = 45,
                            ZoneId = 5
                        },
                        new
                        {
                            Id = 39,
                            XMax = 90,
                            XMin = 75,
                            YMax = 60,
                            YMin = 45,
                            ZoneId = 5
                        },
                        new
                        {
                            Id = 40,
                            XMax = 60,
                            XMin = 45,
                            YMax = 75,
                            YMin = 60,
                            ZoneId = 5
                        },
                        new
                        {
                            Id = 41,
                            XMax = 75,
                            XMin = 60,
                            YMax = 75,
                            YMin = 60,
                            ZoneId = 5
                        },
                        new
                        {
                            Id = 42,
                            XMax = 90,
                            XMin = 75,
                            YMax = 75,
                            YMin = 60,
                            ZoneId = 5
                        },
                        new
                        {
                            Id = 43,
                            XMax = 60,
                            XMin = 45,
                            YMax = 90,
                            YMin = 75,
                            ZoneId = 5
                        },
                        new
                        {
                            Id = 44,
                            XMax = 75,
                            XMin = 60,
                            YMax = 90,
                            YMin = 75,
                            ZoneId = 5
                        },
                        new
                        {
                            Id = 45,
                            XMax = 90,
                            XMin = 75,
                            YMax = 90,
                            YMin = 75,
                            ZoneId = 5
                        },
                        new
                        {
                            Id = 46,
                            XMax = 105,
                            XMin = 90,
                            YMax = 60,
                            YMin = 45,
                            ZoneId = 6
                        },
                        new
                        {
                            Id = 47,
                            XMax = 120,
                            XMin = 105,
                            YMax = 60,
                            YMin = 45,
                            ZoneId = 6
                        },
                        new
                        {
                            Id = 48,
                            XMax = 135,
                            XMin = 120,
                            YMax = 60,
                            YMin = 45,
                            ZoneId = 6
                        },
                        new
                        {
                            Id = 49,
                            XMax = 105,
                            XMin = 90,
                            YMax = 75,
                            YMin = 60,
                            ZoneId = 6
                        },
                        new
                        {
                            Id = 50,
                            XMax = 120,
                            XMin = 105,
                            YMax = 75,
                            YMin = 60,
                            ZoneId = 6
                        },
                        new
                        {
                            Id = 51,
                            XMax = 135,
                            XMin = 120,
                            YMax = 75,
                            YMin = 60,
                            ZoneId = 6
                        },
                        new
                        {
                            Id = 52,
                            XMax = 105,
                            XMin = 90,
                            YMax = 90,
                            YMin = 75,
                            ZoneId = 6
                        },
                        new
                        {
                            Id = 53,
                            XMax = 120,
                            XMin = 105,
                            YMax = 90,
                            YMin = 75,
                            ZoneId = 6
                        },
                        new
                        {
                            Id = 54,
                            XMax = 135,
                            XMin = 120,
                            YMax = 90,
                            YMin = 75,
                            ZoneId = 6
                        },
                        new
                        {
                            Id = 55,
                            XMax = 15,
                            XMin = 0,
                            YMax = 105,
                            YMin = 90,
                            ZoneId = 7
                        },
                        new
                        {
                            Id = 56,
                            XMax = 30,
                            XMin = 15,
                            YMax = 105,
                            YMin = 90,
                            ZoneId = 7
                        },
                        new
                        {
                            Id = 57,
                            XMax = 45,
                            XMin = 30,
                            YMax = 105,
                            YMin = 90,
                            ZoneId = 7
                        },
                        new
                        {
                            Id = 58,
                            XMax = 15,
                            XMin = 0,
                            YMax = 120,
                            YMin = 105,
                            ZoneId = 7
                        },
                        new
                        {
                            Id = 59,
                            XMax = 30,
                            XMin = 15,
                            YMax = 120,
                            YMin = 105,
                            ZoneId = 7
                        },
                        new
                        {
                            Id = 60,
                            XMax = 45,
                            XMin = 30,
                            YMax = 120,
                            YMin = 105,
                            ZoneId = 7
                        },
                        new
                        {
                            Id = 61,
                            XMax = 15,
                            XMin = 0,
                            YMax = 135,
                            YMin = 120,
                            ZoneId = 7
                        },
                        new
                        {
                            Id = 62,
                            XMax = 30,
                            XMin = 15,
                            YMax = 135,
                            YMin = 120,
                            ZoneId = 7
                        },
                        new
                        {
                            Id = 63,
                            XMax = 45,
                            XMin = 30,
                            YMax = 135,
                            YMin = 120,
                            ZoneId = 7
                        },
                        new
                        {
                            Id = 64,
                            XMax = 60,
                            XMin = 45,
                            YMax = 105,
                            YMin = 90,
                            ZoneId = 8
                        },
                        new
                        {
                            Id = 65,
                            XMax = 75,
                            XMin = 60,
                            YMax = 105,
                            YMin = 90,
                            ZoneId = 8
                        },
                        new
                        {
                            Id = 66,
                            XMax = 90,
                            XMin = 75,
                            YMax = 105,
                            YMin = 90,
                            ZoneId = 8
                        },
                        new
                        {
                            Id = 67,
                            XMax = 60,
                            XMin = 45,
                            YMax = 120,
                            YMin = 105,
                            ZoneId = 8
                        },
                        new
                        {
                            Id = 68,
                            XMax = 75,
                            XMin = 60,
                            YMax = 120,
                            YMin = 105,
                            ZoneId = 8
                        },
                        new
                        {
                            Id = 69,
                            XMax = 90,
                            XMin = 75,
                            YMax = 120,
                            YMin = 105,
                            ZoneId = 8
                        },
                        new
                        {
                            Id = 70,
                            XMax = 60,
                            XMin = 45,
                            YMax = 135,
                            YMin = 120,
                            ZoneId = 8
                        },
                        new
                        {
                            Id = 71,
                            XMax = 75,
                            XMin = 60,
                            YMax = 135,
                            YMin = 120,
                            ZoneId = 8
                        },
                        new
                        {
                            Id = 72,
                            XMax = 90,
                            XMin = 75,
                            YMax = 135,
                            YMin = 120,
                            ZoneId = 8
                        },
                        new
                        {
                            Id = 73,
                            XMax = 105,
                            XMin = 90,
                            YMax = 105,
                            YMin = 90,
                            ZoneId = 9
                        },
                        new
                        {
                            Id = 74,
                            XMax = 120,
                            XMin = 105,
                            YMax = 105,
                            YMin = 90,
                            ZoneId = 9
                        },
                        new
                        {
                            Id = 75,
                            XMax = 135,
                            XMin = 120,
                            YMax = 105,
                            YMin = 90,
                            ZoneId = 9
                        },
                        new
                        {
                            Id = 76,
                            XMax = 105,
                            XMin = 90,
                            YMax = 120,
                            YMin = 105,
                            ZoneId = 9
                        },
                        new
                        {
                            Id = 77,
                            XMax = 120,
                            XMin = 105,
                            YMax = 120,
                            YMin = 105,
                            ZoneId = 9
                        },
                        new
                        {
                            Id = 78,
                            XMax = 135,
                            XMin = 120,
                            YMax = 120,
                            YMin = 105,
                            ZoneId = 9
                        },
                        new
                        {
                            Id = 79,
                            XMax = 105,
                            XMin = 90,
                            YMax = 135,
                            YMin = 120,
                            ZoneId = 9
                        },
                        new
                        {
                            Id = 80,
                            XMax = 120,
                            XMin = 105,
                            YMax = 135,
                            YMin = 120,
                            ZoneId = 9
                        },
                        new
                        {
                            Id = 81,
                            XMax = 135,
                            XMin = 120,
                            YMax = 135,
                            YMin = 120,
                            ZoneId = 9
                        },
                        new
                        {
                            Id = 82,
                            XMax = 15,
                            XMin = 0,
                            YMax = 150,
                            YMin = 135,
                            ZoneId = 10
                        },
                        new
                        {
                            Id = 83,
                            XMax = 30,
                            XMin = 15,
                            YMax = 150,
                            YMin = 135,
                            ZoneId = 10
                        },
                        new
                        {
                            Id = 84,
                            XMax = 45,
                            XMin = 30,
                            YMax = 150,
                            YMin = 135,
                            ZoneId = 10
                        },
                        new
                        {
                            Id = 85,
                            XMax = 15,
                            XMin = 0,
                            YMax = 165,
                            YMin = 150,
                            ZoneId = 10
                        },
                        new
                        {
                            Id = 86,
                            XMax = 30,
                            XMin = 15,
                            YMax = 165,
                            YMin = 150,
                            ZoneId = 10
                        },
                        new
                        {
                            Id = 87,
                            XMax = 45,
                            XMin = 30,
                            YMax = 165,
                            YMin = 150,
                            ZoneId = 10
                        },
                        new
                        {
                            Id = 88,
                            XMax = 15,
                            XMin = 0,
                            YMax = 180,
                            YMin = 165,
                            ZoneId = 10
                        },
                        new
                        {
                            Id = 89,
                            XMax = 30,
                            XMin = 15,
                            YMax = 180,
                            YMin = 165,
                            ZoneId = 10
                        },
                        new
                        {
                            Id = 90,
                            XMax = 45,
                            XMin = 30,
                            YMax = 180,
                            YMin = 165,
                            ZoneId = 10
                        },
                        new
                        {
                            Id = 91,
                            XMax = 60,
                            XMin = 45,
                            YMax = 150,
                            YMin = 135,
                            ZoneId = 11
                        },
                        new
                        {
                            Id = 92,
                            XMax = 75,
                            XMin = 60,
                            YMax = 150,
                            YMin = 135,
                            ZoneId = 11
                        },
                        new
                        {
                            Id = 93,
                            XMax = 90,
                            XMin = 75,
                            YMax = 150,
                            YMin = 135,
                            ZoneId = 11
                        },
                        new
                        {
                            Id = 94,
                            XMax = 60,
                            XMin = 45,
                            YMax = 165,
                            YMin = 150,
                            ZoneId = 11
                        },
                        new
                        {
                            Id = 95,
                            XMax = 75,
                            XMin = 60,
                            YMax = 165,
                            YMin = 150,
                            ZoneId = 11
                        },
                        new
                        {
                            Id = 96,
                            XMax = 90,
                            XMin = 75,
                            YMax = 165,
                            YMin = 150,
                            ZoneId = 11
                        },
                        new
                        {
                            Id = 97,
                            XMax = 60,
                            XMin = 45,
                            YMax = 180,
                            YMin = 165,
                            ZoneId = 11
                        },
                        new
                        {
                            Id = 98,
                            XMax = 75,
                            XMin = 60,
                            YMax = 180,
                            YMin = 165,
                            ZoneId = 11
                        },
                        new
                        {
                            Id = 99,
                            XMax = 90,
                            XMin = 75,
                            YMax = 180,
                            YMin = 165,
                            ZoneId = 11
                        },
                        new
                        {
                            Id = 100,
                            XMax = 105,
                            XMin = 90,
                            YMax = 150,
                            YMin = 135,
                            ZoneId = 12
                        },
                        new
                        {
                            Id = 101,
                            XMax = 120,
                            XMin = 105,
                            YMax = 150,
                            YMin = 135,
                            ZoneId = 12
                        },
                        new
                        {
                            Id = 102,
                            XMax = 135,
                            XMin = 120,
                            YMax = 150,
                            YMin = 135,
                            ZoneId = 12
                        },
                        new
                        {
                            Id = 103,
                            XMax = 105,
                            XMin = 90,
                            YMax = 165,
                            YMin = 150,
                            ZoneId = 12
                        },
                        new
                        {
                            Id = 104,
                            XMax = 120,
                            XMin = 105,
                            YMax = 165,
                            YMin = 150,
                            ZoneId = 12
                        },
                        new
                        {
                            Id = 105,
                            XMax = 135,
                            XMin = 120,
                            YMax = 165,
                            YMin = 150,
                            ZoneId = 12
                        },
                        new
                        {
                            Id = 106,
                            XMax = 105,
                            XMin = 90,
                            YMax = 180,
                            YMin = 165,
                            ZoneId = 12
                        },
                        new
                        {
                            Id = 107,
                            XMax = 120,
                            XMin = 105,
                            YMax = 180,
                            YMin = 165,
                            ZoneId = 12
                        },
                        new
                        {
                            Id = 108,
                            XMax = 135,
                            XMin = 120,
                            YMax = 180,
                            YMin = 165,
                            ZoneId = 12
                        },
                        new
                        {
                            Id = 109,
                            XMax = 15,
                            XMin = 0,
                            YMax = 195,
                            YMin = 180,
                            ZoneId = 13
                        },
                        new
                        {
                            Id = 110,
                            XMax = 30,
                            XMin = 15,
                            YMax = 195,
                            YMin = 180,
                            ZoneId = 13
                        },
                        new
                        {
                            Id = 111,
                            XMax = 45,
                            XMin = 30,
                            YMax = 195,
                            YMin = 180,
                            ZoneId = 13
                        },
                        new
                        {
                            Id = 112,
                            XMax = 15,
                            XMin = 0,
                            YMax = 210,
                            YMin = 195,
                            ZoneId = 13
                        },
                        new
                        {
                            Id = 113,
                            XMax = 30,
                            XMin = 15,
                            YMax = 210,
                            YMin = 195,
                            ZoneId = 13
                        },
                        new
                        {
                            Id = 114,
                            XMax = 45,
                            XMin = 30,
                            YMax = 210,
                            YMin = 195,
                            ZoneId = 13
                        },
                        new
                        {
                            Id = 115,
                            XMax = 15,
                            XMin = 0,
                            YMax = 225,
                            YMin = 210,
                            ZoneId = 13
                        },
                        new
                        {
                            Id = 116,
                            XMax = 30,
                            XMin = 15,
                            YMax = 225,
                            YMin = 210,
                            ZoneId = 13
                        },
                        new
                        {
                            Id = 117,
                            XMax = 45,
                            XMin = 30,
                            YMax = 225,
                            YMin = 210,
                            ZoneId = 13
                        },
                        new
                        {
                            Id = 118,
                            XMax = 60,
                            XMin = 45,
                            YMax = 195,
                            YMin = 180,
                            ZoneId = 14
                        },
                        new
                        {
                            Id = 119,
                            XMax = 75,
                            XMin = 60,
                            YMax = 195,
                            YMin = 180,
                            ZoneId = 14
                        },
                        new
                        {
                            Id = 120,
                            XMax = 90,
                            XMin = 75,
                            YMax = 195,
                            YMin = 180,
                            ZoneId = 14
                        },
                        new
                        {
                            Id = 121,
                            XMax = 60,
                            XMin = 45,
                            YMax = 210,
                            YMin = 195,
                            ZoneId = 14
                        },
                        new
                        {
                            Id = 122,
                            XMax = 75,
                            XMin = 60,
                            YMax = 210,
                            YMin = 195,
                            ZoneId = 14
                        },
                        new
                        {
                            Id = 123,
                            XMax = 90,
                            XMin = 75,
                            YMax = 210,
                            YMin = 195,
                            ZoneId = 14
                        },
                        new
                        {
                            Id = 124,
                            XMax = 60,
                            XMin = 45,
                            YMax = 225,
                            YMin = 210,
                            ZoneId = 14
                        },
                        new
                        {
                            Id = 125,
                            XMax = 75,
                            XMin = 60,
                            YMax = 225,
                            YMin = 210,
                            ZoneId = 14
                        },
                        new
                        {
                            Id = 126,
                            XMax = 90,
                            XMin = 75,
                            YMax = 225,
                            YMin = 210,
                            ZoneId = 14
                        },
                        new
                        {
                            Id = 127,
                            XMax = 105,
                            XMin = 90,
                            YMax = 195,
                            YMin = 180,
                            ZoneId = 15
                        },
                        new
                        {
                            Id = 128,
                            XMax = 120,
                            XMin = 105,
                            YMax = 195,
                            YMin = 180,
                            ZoneId = 15
                        },
                        new
                        {
                            Id = 129,
                            XMax = 135,
                            XMin = 120,
                            YMax = 195,
                            YMin = 180,
                            ZoneId = 15
                        },
                        new
                        {
                            Id = 130,
                            XMax = 105,
                            XMin = 90,
                            YMax = 210,
                            YMin = 195,
                            ZoneId = 15
                        },
                        new
                        {
                            Id = 131,
                            XMax = 120,
                            XMin = 105,
                            YMax = 210,
                            YMin = 195,
                            ZoneId = 15
                        },
                        new
                        {
                            Id = 132,
                            XMax = 135,
                            XMin = 120,
                            YMax = 210,
                            YMin = 195,
                            ZoneId = 15
                        },
                        new
                        {
                            Id = 133,
                            XMax = 105,
                            XMin = 90,
                            YMax = 225,
                            YMin = 210,
                            ZoneId = 15
                        },
                        new
                        {
                            Id = 134,
                            XMax = 120,
                            XMin = 105,
                            YMax = 225,
                            YMin = 210,
                            ZoneId = 15
                        },
                        new
                        {
                            Id = 135,
                            XMax = 135,
                            XMin = 120,
                            YMax = 225,
                            YMin = 210,
                            ZoneId = 15
                        });
                });

            modelBuilder.Entity("MapApi.Entities.MapItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<int>("CoordX")
                        .HasColumnType("integer");

                    b.Property<int>("CoordY")
                        .HasColumnType("integer");

                    b.Property<bool>("IsApe")
                        .HasColumnType("boolean");

                    b.Property<int>("MapItemTypeId")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("MapItemTypeId");

                    b.ToTable("MapItem");
                });

            modelBuilder.Entity("MapApi.Entities.MapItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MapItemType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Player"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Gate"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "UnAssignedCenter"
                        });
                });

            modelBuilder.Entity("MapApi.Entities.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("XMax")
                        .HasColumnType("integer");

                    b.Property<int>("XMin")
                        .HasColumnType("integer");

                    b.Property<int>("YMax")
                        .HasColumnType("integer");

                    b.Property<int>("YMin")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Zone");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            XMax = 45,
                            XMin = 0,
                            YMax = 45,
                            YMin = 0
                        },
                        new
                        {
                            Id = 2,
                            XMax = 90,
                            XMin = 45,
                            YMax = 45,
                            YMin = 0
                        },
                        new
                        {
                            Id = 3,
                            XMax = 135,
                            XMin = 90,
                            YMax = 45,
                            YMin = 0
                        },
                        new
                        {
                            Id = 4,
                            XMax = 45,
                            XMin = 0,
                            YMax = 90,
                            YMin = 45
                        },
                        new
                        {
                            Id = 5,
                            XMax = 90,
                            XMin = 45,
                            YMax = 90,
                            YMin = 45
                        },
                        new
                        {
                            Id = 6,
                            XMax = 135,
                            XMin = 90,
                            YMax = 90,
                            YMin = 45
                        },
                        new
                        {
                            Id = 7,
                            XMax = 45,
                            XMin = 0,
                            YMax = 135,
                            YMin = 90
                        },
                        new
                        {
                            Id = 8,
                            XMax = 90,
                            XMin = 45,
                            YMax = 135,
                            YMin = 90
                        },
                        new
                        {
                            Id = 9,
                            XMax = 135,
                            XMin = 90,
                            YMax = 135,
                            YMin = 90
                        },
                        new
                        {
                            Id = 10,
                            XMax = 45,
                            XMin = 0,
                            YMax = 180,
                            YMin = 135
                        },
                        new
                        {
                            Id = 11,
                            XMax = 90,
                            XMin = 45,
                            YMax = 180,
                            YMin = 135
                        },
                        new
                        {
                            Id = 12,
                            XMax = 135,
                            XMin = 90,
                            YMax = 180,
                            YMin = 135
                        },
                        new
                        {
                            Id = 13,
                            XMax = 45,
                            XMin = 0,
                            YMax = 225,
                            YMin = 180
                        },
                        new
                        {
                            Id = 14,
                            XMax = 90,
                            XMin = 45,
                            YMax = 225,
                            YMin = 180
                        },
                        new
                        {
                            Id = 15,
                            XMax = 135,
                            XMin = 90,
                            YMax = 225,
                            YMin = 180
                        });
                });

            modelBuilder.Entity("SharedLibrary.Entities.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text");

                    b.Property<string>("AppVersion")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<string>("DeviceModel")
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text");

                    b.Property<double?>("Duration")
                        .HasColumnType("double precision");

                    b.Property<string>("EventId")
                        .HasColumnType("text");

                    b.Property<string>("EventName")
                        .HasColumnType("text");

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<string>("InnerException")
                        .HasColumnType("text");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OsVersion")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("SharedLibrary.Entities.LogAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text");

                    b.Property<string>("AppVersion")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<string>("DeviceModel")
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .HasColumnType("text");

                    b.Property<double?>("Duration")
                        .HasColumnType("double precision");

                    b.Property<string>("EventId")
                        .HasColumnType("text");

                    b.Property<string>("EventName")
                        .HasColumnType("text");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OsVersion")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("LogAction");
                });

            modelBuilder.Entity("MapApi.Entities.Area", b =>
                {
                    b.HasOne("MapApi.Entities.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("MapApi.Entities.MapItem", b =>
                {
                    b.HasOne("MapApi.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MapApi.Entities.MapItemType", "MapItemType")
                        .WithMany()
                        .HasForeignKey("MapItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("MapItemType");
                });
#pragma warning restore 612, 618
        }
    }
}
