// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProgressApi;

#nullable disable

namespace ProgressApi.Migrations
{
    [DbContext(typeof(ProgressContext))]
    [Migration("20220628163449_init_migration")]
    partial class init_migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProgressApi.Entities.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Stage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "FirstStage"
                        });
                });

            modelBuilder.Entity("ProgressApi.Entities.UserProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<int?>("EndGameScore")
                        .HasColumnType("integer");

                    b.Property<int?>("FailCount")
                        .HasColumnType("integer");

                    b.Property<string>("Ip")
                        .HasColumnType("text");

                    b.Property<int?>("KillCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LevelEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LevelStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("StageId")
                        .HasColumnType("integer");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("UserProcess");
                });

            modelBuilder.Entity("ProgressApi.Entities.UserProgress", b =>
                {
                    b.HasOne("ProgressApi.Entities.Stage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId");

                    b.Navigation("Stage");
                });
#pragma warning restore 612, 618
        }
    }
}
